In [1]:
import numpy as np

a = np.array([[1,1], [1,1]])  
b = np.array([[11,12], [21,22]]) 
print(np.kron(a, b))  
print(np.kron(b, a))

[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]
[[11 11 12 12]
 [11 11 12 12]
 [21 21 22 22]
 [21 21 22 22]]


In [2]:
from mindquantum import Simulator, Circuit, X, Y
import numpy as np
s0 = np.array([0.1, 0.4]) 
sim = Simulator('projectq', 1)  
sim.set_qs(s0)  
print(sim.get_qs()) 
sim.apply_gate(X.on(0)) 
print(sim.get_qs())

[0.24253563+0.j 0.9701425 +0.j]
[0.9701425 +0.j 0.24253563+0.j]
