In [1]:
import numpy as np                                    # 导入numpy库并简写为np
from mindquantum.core import  X, Y, Z, H, RX, RY, RZ   # 导入量子门H, X, Y, Z, RX, RY, RZ
from mindquantum import Simulator, Circuit

In [2]:
A =np.array([[1,1],[1,1]])
print(A)
B = np.array([[11,12],[21,22]])
print(B)
KronC = np.kron(A,B)
print(KronC)

[[1 1]
 [1 1]]
[[11 12]
 [21 22]]
[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]


In [3]:
s0 = np.array([1,0])

sim = Simulator('projectq',1)
sim.set_qs(s0)
print(sim.get_qs())
circ1 = Circuit([Y.on(0), X.on(0), Y.on(0)])
sim.apply_circuit(circ1)
print(sim.get_qs())
circ2 = Circuit([X.on(0)])
sim.apply_circuit(circ2)
print(sim.get_qs())




[1.+0.j 0.+0.j]
[ 0.+0.j -1.+0.j]
[-1.+0.j  0.+0.j]
