# Day 1
## 1.1 多比特的量子态矢量或矩阵的张量乘积计算
$$
|\psi \rangle \otimes |\phi\rangle = \left(\begin{matrix} a \\ b \end{matrix}\right) \otimes \left(\begin{matrix} c \\ d \end{matrix}\right)
= \left(\begin{matrix} c\left(\begin{matrix} a \\ b \end{matrix}\right) \\ d\left(\begin{matrix} a \\ b \end{matrix}\right) \end{matrix}\right)
= \left(\begin{matrix} ac \\ ad \\ bc \\ bd \end{matrix}\right)
$$

### 请完成：
请利用numpy完成下面两个矩阵的张量乘法：
$$
A=\left(\begin{matrix}
1 & 1 \\ 1 &1
\end{matrix}\right),
B=\left(\begin{matrix}
11 & 12 \\21&22
\end{matrix}\right).
$$
请计算$A\otimes B$和$B\otimes A$.


In [3]:
import numpy as np
#态张量乘积示例

#一般性的多矢量张量乘法函数
def kron(state_list):
    res = state_list[0]
    for state in state_list[1:]:
        res = np.kron(res, state)
    return res

s0 = np.array([[1, 1],[1,1]])
s1 = np.array([[11, 12],[21,22]])
s01 = np.kron(s0, s1)
print(s01)
s10 = np.kron(s1, s0)
print(s10)

[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]
[[11 11 12 12]
 [11 11 12 12]
 [21 21 22 22]
 [21 21 22 22]]


## 1.2 基本单比特旋转门之间的变换关系
量子力学中的对易关系(commutation relationship)，可以进行一些量子门之间的相互转化：
$$\left[ X, Y\right] = XY-YX=2iZ,$$
$$\left[ Y, Z\right] = YZ-ZY=2iX,$$
$$\left[ Z, X\right] = ZX-XZ=2iY,$$
$$ \left[ X, X\right] = \left[ Y, Y\right] = \left[ Z, Z\right] = 0$$
以及反对易关系(anti-commutation relationship):
$$\{ X, Y\} =XY + YX = 0,$$
$$\{ Z, Y\} =ZY + YZ = 0,$$
$$\{ X, Z\} =XZ + ZX = 0,$$
如
$$YZY|\psi\rangle = -Z|\psi\rangle$$

### 请完成：
X, Y门之间的变换展示

In [12]:
from mindquantum import Simulator, Circuit, X, Y, Z
import numpy as np
#任意态
s0 = np.array([1, 0]) .transpose()
s1 = np.array([0, 1]) .transpose()
s01 = s0+s1
sim = Simulator('projectq', 1)
sim.set_qs(s01)
print(sim.set_qs(s01))

#ZX
circ1 = Circuit([Z.on(0), X.on(0)]) 
sim.apply_circuit(circ1)
print(sim.get_qs())

#Y
sim.set_qs(s01)
sim.apply_gate(Y.on(0))
print(sim.get_qs())

None
[-0.70710678+0.j  0.70710678+0.j]
[0.-0.70710678j 0.+0.70710678j]
