# Day 1
## 1.1 多比特的量子态矢量或矩阵的张量乘积计算
$$
|\psi \rangle \otimes |\phi\rangle = \left(\begin{matrix} a \\ b \end{matrix}\right) \otimes \left(\begin{matrix} c \\ d \end{matrix}\right)
= \left(\begin{matrix} c\left(\begin{matrix} a \\ b \end{matrix}\right) \\ d\left(\begin{matrix} a \\ b \end{matrix}\right) \end{matrix}\right)
= \left(\begin{matrix} ac \\ ad \\ bc \\ bd \end{matrix}\right)
$$

### 请完成：
请利用numpy完成下面两个矩阵的张量乘法：
$$
A=\left(\begin{matrix}
1 & 1 \\ 1 &1
\end{matrix}\right),
B=\left(\begin{matrix}
11 & 12 \\21&22
\end{matrix}\right).
$$
请计算$A\otimes B$和$B\otimes A$.


In [3]:
import numpy as np

A = np.array([[1, 1], [1, 1]])
B = np.array([[11, 12], [21, 22]])
A_product_B = np.kron(A, B)
B_product_A = np.kron(B, A)
print('A⊗B = \n{}'.format(A_product_B))
print()
print('B⊗A = \n{}'.format(B_product_A))


A⊗B = 
[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]

B⊗A = 
[[11 11 12 12]
 [11 11 12 12]
 [21 21 22 22]
 [21 21 22 22]]


## 1.2 基本单比特旋转门之间的变换关系
量子力学中的对易关系(commutation relationship)，可以进行一些量子门之间的相互转化：
$$\left[ X, Y\right] = XY-YX=2iZ,$$
$$\left[ Y, Z\right] = YZ-ZY=2iX,$$
$$\left[ Z, X\right] = ZX-XZ=2iY,$$
$$ \left[ X, X\right] = \left[ Y, Y\right] = \left[ Z, Z\right] = 0$$
以及反对易关系(anti-commutation relationship):
$$\{ X, Y\} =XY + YX = 0,$$
$$\{ Z, Y\} =ZY + YZ = 0,$$
$$\{ X, Z\} =XZ + ZX = 0,$$
如
$$YZY|\psi\rangle = -Z|\psi\rangle$$

### 请完成：
X, Y门之间的变换展示

$$XX=I \implies Y=XXY,Y=YXX\cdots$$
$$X=-YXY$$
$$Y=-XYX$$

In [4]:
from mindquantum import Simulator, Circuit, X, Y
import numpy as np

sim = Simulator('projectq', 1)
sim.set_qs(np.array([0.25, 0.1]))  # 可修改
s0 = sim.get_qs() # 归一化后的quantum state
print('s0=', s0)

# XX
sim.set_qs(s0)
sim.apply_circuit(Circuit([X.on(0), X.on(0)]))
XXs0 = sim.get_qs()
print('XXs0=', XXs0)

if np.allclose(s0, XXs0):
    print('XX = I')
print()

# X
sim.set_qs(s0)
sim.apply_gate(X.on(0))
Xs0 = sim.get_qs()
print('Xs0=', Xs0)

# YXY
sim.set_qs(s0)
sim.apply_circuit(Circuit([Y.on(0), X.on(0), Y.on(0)]))
YXYs0 = sim.get_qs()
print('YXYs0=', YXYs0)

if np.allclose(Xs0, np.multiply(-1, YXYs0)):
    print('X = -YXY')
print()

# Y
sim.set_qs(s0)
sim.apply_gate(Y.on(0))
Ys0 = sim.get_qs()
print('Ys0=', Ys0)

# XYX
sim.set_qs(s0)
sim.apply_circuit(Circuit([X.on(0), Y.on(0), X.on(0)]))
XYXs0 = sim.get_qs()
print('XYXs0=', XYXs0)

if np.allclose(Ys0, np.multiply(-1, XYXs0)):
    print('Y = -XYX')
print()


s0= [0.92847669+0.j 0.37139068+0.j]
XXs0= [0.92847669+0.j 0.37139068+0.j]
XX = I

Xs0= [0.37139068+0.j 0.92847669+0.j]
YXYs0= [-0.37139068+0.j -0.92847669+0.j]
X = -YXY

Ys0= [0.-0.37139068j 0.+0.92847669j]
XYXs0= [0.+0.37139068j 0.-0.92847669j]
Y = -XYX

