In [16]:
import numpy as np 

A= np.array([[1,1],
[1,1]])
B= np.array([[11,12],
[21,22]])

#print(A)
#print(B)
A_B = np.kron(A,B)
B_A = np.kron(A,B)
print(A_B)

[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]
