# Day 1
## 1.1 多比特的量子态矢量或矩阵的张量乘积计算
$$
|\psi \rangle \otimes |\phi\rangle = \left(\begin{matrix} a \\ b \end{matrix}\right) \otimes \left(\begin{matrix} c \\ d \end{matrix}\right)
= \left(\begin{matrix} c\left(\begin{matrix} a \\ b \end{matrix}\right) \\ d\left(\begin{matrix} a \\ b \end{matrix}\right) \end{matrix}\right)
= \left(\begin{matrix} ac \\ ad \\ bc \\ bd \end{matrix}\right)
$$

### 请完成：
请利用numpy完成下面两个矩阵的张量乘法：
$$
A=\left(\begin{matrix}
1 & 1 \\ 1 &1
\end{matrix}\right),
B=\left(\begin{matrix}
11 & 12 \\21&22
\end{matrix}\right).
$$
请计算$A\otimes B$和$B\otimes A$.


In [9]:
import numpy as np
#态张量乘积示例

#一般性的多矢量张量乘法函数
def kron(state_list):
    res = state_list[0]
    for state in state_list[1:]:
        res = np.kron(res, state)
    return res

A = np.array([[1, 1],[1,1]]).transpose()
B = np.array([[11, 12],[21, 22]]).transpose()
A_B = np.kron(A, B)
B_A = np.kron(B, A)
#s001 = kron([s0, s0, s1])
print("A_B:")
print(A_B)
print("B_A:")
print(B_A)

A_B:
[[11 21 11 21]
 [12 22 12 22]
 [11 21 11 21]
 [12 22 12 22]]
B_A:
[[11 11 21 21]
 [11 11 21 21]
 [12 12 22 22]
 [12 12 22 22]]


## 1.2 基本单比特旋转门之间的变换关系
量子力学中的对易关系(commutation relationship)，可以进行一些量子门之间的相互转化：
$$\left[ X, Y\right] = XY-YX=2iZ,$$
$$\left[ Y, Z\right] = YZ-ZY=2iX,$$
$$\left[ Z, X\right] = ZX-XZ=2iY,$$
$$ \left[ X, X\right] = \left[ Y, Y\right] = \left[ Z, Z\right] = 0$$
以及反对易关系(anti-commutation relationship):
$$\{ X, Y\} =XY + YX = 0,$$
$$\{ Z, Y\} =ZY + YZ = 0,$$
$$\{ X, Z\} =XZ + ZX = 0,$$
如
$$YZY|\psi\rangle = -Z|\psi\rangle$$

### 请完成：
X, Y门之间的变换展示

In [1]:
from mindquantum import Simulator, Circuit, X, Y, Z
import numpy as np
#任意态
s0 = np.array([10, 20]) #可修改
s0_test = np.array([100, 200])
sim = Simulator('projectq', 1)
sim.set_qs(s0)
#print(sim.get_qs())

#X
sim.set_qs(s0)
sim.apply_gate(X.on(0))
print("X:")
print(sim.get_qs())

#Y
sim.set_qs(s0)
sim.apply_gate(Y.on(0))
print("Y:")
print(sim.get_qs())

#XY
sim.reset()
sim.set_qs(np.array([1,1]))
circ_XY = Circuit([X.on(0), Y.on(0)]) 
sim.apply_circuit(circ_XY)
print("XY:")
print(sim.get_qs())

#YX
sim.reset()
sim.set_qs(np.array([1,1]))
circ_YX = Circuit([Y.on(0), X.on(0)]) 
sim.apply_circuit(circ_YX)
print("YX:")
print(sim.get_qs())

X:
[0.89442719+0.j 0.4472136 +0.j]
Y:
[0.-0.89442719j 0.+0.4472136j ]
XY:
[0.-0.70710678j 0.+0.70710678j]
YX:
[0.+0.70710678j 0.-0.70710678j]
