# Day 1
## 1.1 多比特的量子态矢量或矩阵的张量乘积计算
$$
|\psi \rangle \otimes |\phi\rangle = \left(\begin{matrix} a \\ b \end{matrix}\right) \otimes \left(\begin{matrix} c \\ d \end{matrix}\right)
= \left(\begin{matrix} c\left(\begin{matrix} a \\ b \end{matrix}\right) \\ d\left(\begin{matrix} a \\ b \end{matrix}\right) \end{matrix}\right)
= \left(\begin{matrix} ac \\ ad \\ bc \\ bd \end{matrix}\right)
$$

### 请完成：
请利用numpy完成下面两个矩阵的张量乘法：
$$
A=\left(\begin{matrix}
1 & 1 \\ 1 &1
\end{matrix}\right),
B=\left(\begin{matrix}
11 & 12 \\21&22
\end{matrix}\right).
$$
请计算$A\otimes B$和$B\otimes A$.


In [7]:
import numpy as np
#态张量乘积示例

#一般性的多矢量张量乘法函数
def kron(state_list):
    res = state_list[0]
    for state in state_list[1:]:
        res = np.kron(res, state)
    return res

s0 = np.array([1, 0]).transpose()
s1 = np.array([0, 1]).transpose()
s00 = np.kron(s0, s0)
s001 = kron([s0, s0, s1])
print(s00)
print(s001)
A = np.array([[1, 1],[1, 1]]).transpose()
B = np.array([[11, 12],[21, 22]]).transpose()
A_B = np.kron(A, B)
B_A = np.kron(B, A)
print("A_B:\n",A_B)
print("B_A:\n",B_A)

[1 0 0 0]
[0 1 0 0 0 0 0 0]
A_B:
 [[11 21 11 21]
 [12 22 12 22]
 [11 21 11 21]
 [12 22 12 22]]
B_A:
 [[11 11 21 21]
 [11 11 21 21]
 [12 12 22 22]
 [12 12 22 22]]


In [7]:
# homework
import numpy as np
A = np.array([[1, 1],[1, 1]]).transpose()
B = np.array([[11, 12],[21, 22]]).transpose()
A_B = np.kron(A, B)
B_A = np.kron(B, A)
print("A:\n",A)
print("B:\n",B)
print("A_B:\n",A_B)
print("B_A:\n",B_A)

A:
 [[1 1]
 [1 1]]
B:
 [[11 21]
 [12 22]]
A_B:
 [[11 21 11 21]
 [12 22 12 22]
 [11 21 11 21]
 [12 22 12 22]]
B_A:
 [[11 11 21 21]
 [11 11 21 21]
 [12 12 22 22]
 [12 12 22 22]]


## 1.2 基本单比特旋转门之间的变换关系
量子力学中的对易关系(commutation relationship)，可以进行一些量子门之间的相互转化：
$$\left[ X, Y\right] = XY-YX=2iZ,$$
$$\left[ Y, Z\right] = YZ-ZY=2iX,$$
$$\left[ Z, X\right] = ZX-XZ=2iY,$$
$$ \left[ X, X\right] = \left[ Y, Y\right] = \left[ Z, Z\right] = 0$$
以及反对易关系(anti-commutation relationship):
$$\{ X, Y\} =XY + YX = 0,$$
$$\{ Z, Y\} =ZY + YZ = 0,$$
$$\{ X, Z\} =XZ + ZX = 0,$$
如
$$YZY|\psi\rangle = -Z|\psi\rangle$$

### 请完成：
X, Y门之间的变换展示

In [8]:
from mindquantum import Simulator, Circuit, X, Y, Z, RX, RY, RZ
import numpy as np
#任意态
s0 = np.array([0.25, 0.1]) #可修改
s0_test = np.array([100, 200])
sim = Simulator('projectq', 1)
sim.set_qs(s0)
print(sim.get_qs())

#YZY
circ1 = Circuit([Y.on(0), Z.on(0), Y.on(0)]) 
sim.apply_circuit(circ1)
print(sim.get_qs())

#Z
sim.set_qs(s0)
sim.apply_gate(Z.on(0))
print(sim.get_qs())


[0.92847669+0.j 0.37139068+0.j]
[-0.92847669+0.j  0.37139068+0.j]
[ 0.92847669+0.j -0.37139068+0.j]


In [9]:
# homework
from mindquantum import Simulator, Circuit, X, Y, Z, RX, RY, RZ
import numpy as np
#任意态
s0 = np.array([0.25, 0.1]) #可修改
s0_test = np.array([100, 200])
sim = Simulator('projectq', 1)
sim.set_qs(s0)
print(sim.get_qs())

#XYX
circ1 = Circuit([X.on(0), Y.on(0), X.on(0)]) 
sim.apply_circuit(circ1)
print("XYX:\n",sim.get_qs())

#Y
sim.set_qs(s0)
sim.apply_gate(Y.on(0))
print("Y:\n",sim.get_qs())

# print("X:\n",X.matrix())
# print("Y:\n",Y.matrix())
# ry = RY('theta')
# rx = RX('theta')
# rz = RZ('theta')
# I = rx.matrix({'theta': 0})
# H = ry.matrix({'theta': np.pi/2})
# Z = rz.matrix({'theta': np.pi})
# print("I:\n",I)
# print("H:\n",H)
# print("Z:\n",np.round(Z))

[0.92847669+0.j 0.37139068+0.j]
XYX:
 [0.+0.37139068j 0.-0.92847669j]
Y:
 [0.-0.37139068j 0.+0.92847669j]
