# Day 1
## 1.1 多比特的量子态矢量或矩阵的张量乘积计算
$$
|\psi \rangle \otimes |\phi\rangle = \left(\begin{matrix} a \\ b \end{matrix}\right) \otimes \left(\begin{matrix} c \\ d \end{matrix}\right)
= \left(\begin{matrix} a\left(\begin{matrix} c \\ d \end{matrix}\right) \\ b\left(\begin{matrix} c \\ d \end{matrix}\right) \end{matrix}\right)
= \left(\begin{matrix} ac \\ ad \\ bc \\ bd \end{matrix}\right)
$$

### 请完成：
请利用numpy完成下面两个矩阵的张量乘法：
$$
A=\left(\begin{matrix}
1 & 1 \\ 1 &1
\end{matrix}\right),
B=\left(\begin{matrix}
11 & 12 \\21&22
\end{matrix}\right).
$$
请计算$A\otimes B$和$B\otimes A$.

In [9]:
import numpy as np 

A=np.array([[1,1],[1,1]])
B=np.array([[11,22],[21,22]])

kronx=np.kron(A,B)
krony=np.kron(B,A)

print("A:\n:",A)
print("B::\n",B)
print("A⊗B:\n",kronx)
print("B⊗A:\n",krony)

A:
: [[1 1]
 [1 1]]
B::
 [[11 22]
 [21 22]]
A⊗B:
 [[11 22 11 22]
 [21 22 21 22]
 [11 22 11 22]
 [21 22 21 22]]
B⊗A:
 [[11 11 22 22]
 [11 11 22 22]
 [21 21 22 22]
 [21 21 22 22]]


## 1.2 基本单比特旋转门之间的变换关系
量子力学中的对易关系(commutation relationship)，可以进行一些量子门之间的相互转化：
$$\left[ X, Y\right] = XY-YX=2iZ,$$
$$\left[ Y, Z\right] = YZ-ZY=2iX,$$
$$\left[ Z, X\right] = ZX-XZ=2iY,$$
$$ \left[ X, X\right] = \left[ Y, Y\right] = \left[ Z, Z\right] = 0$$
以及反对易关系(anti-commutation relationship):
$$\{ X, Y\} =XY + YX = 0,$$
$$\{ Z, Y\} =ZY + YZ = 0,$$
$$\{ X, Z\} =XZ + ZX = 0,$$
如
$$YZY|\psi\rangle = -Z|\psi\rangle$$

### 请完成：
X, Y门之间的变换展示

In [37]:
from mindquantum import Simulator, Circuit, X, Y, Z
import numpy as np
#任意态
s0 = np.array([1, 2]) #可修改
sim = Simulator('projectq', 1)
sim.set_qs(s0)
print(sim.get_qs())
#X
sim.set_qs(s0)
sim.apply_gate(X.on(0))
print("X:", sim.get_qs())
#Y
sim.set_qs(s0)
sim.apply_gate(Y.on(0))
print("Y:", sim.get_qs())
#Z
sim.set_qs(s0)
sim.apply_gate(Z.on(0))
print("Z:", sim.get_qs())

#XX
sim.set_qs(s0)
circ1 = Circuit([X.on(0), X.on(0)]) 
sim.apply_circuit(circ1)
print("XX:", sim.get_qs())

#YY
sim.set_qs(s0)
circ1 = Circuit([Y.on(0), Y.on(0)]) 
sim.apply_circuit(circ1)
print("YY:", sim.get_qs())

#XY
sim.set_qs(s0)
circ1 = Circuit([X.on(0), Y.on(0)]) 
sim.apply_circuit(circ1)
print("XY:", sim.get_qs())

#YX
sim.set_qs(s0)
circ1 = Circuit([Y.on(0), X.on(0)]) 
sim.apply_circuit(circ1)
print("YX:", sim.get_qs())

#XYX
sim.set_qs(s0)
circ1 = Circuit([X.on(0), Y.on(0), X.on(0)]) 
sim.apply_circuit(circ1)
print("XYX:", sim.get_qs())

#YXY
sim.set_qs(s0)
circ1 = Circuit([Y.on(0), X.on(0), Y.on(0)]) 
sim.apply_circuit(circ1)
print("YXY:", sim.get_qs())



[0.4472136 +0.j 0.89442719+0.j]
X: [0.89442719+0.j 0.4472136 +0.j]
Y: [0.-0.89442719j 0.+0.4472136j ]
Z: [ 0.4472136 +0.j -0.89442719+0.j]
XX: [0.4472136 +0.j 0.89442719+0.j]
YY: [0.4472136 +0.j 0.89442719+0.j]
XY: [0.-0.4472136j  0.+0.89442719j]
YX: [0.+0.4472136j  0.-0.89442719j]
XYX: [0.+0.89442719j 0.-0.4472136j ]
YXY: [-0.89442719+0.j -0.4472136 +0.j]


可以得到如下关系：
$$XYX|\psi\rangle = -Y|\psi\rangle$$
$$YXY|\psi\rangle = -X|\psi\rangle$$
$$XY|\psi\rangle = i*Z|\psi\rangle$$
$$XY|\psi\rangle = -YX|\psi\rangle$$
$$XX|\psi\rangle = |\psi\rangle$$
$$YY|\psi\rangle = |\psi\rangle$$
