In [7]:
import numpy as np

a = np.array([[1,1], [1,1]])   # 初始化 a 矩阵
b = np.array([[11,12], [21,22]])   # 初始化 b 矩阵
print(np.kron(a, b))   # 计算 a b 的张量积

[[11 12 11 12]
 [21 22 21 22]
 [11 12 11 12]
 [21 22 21 22]]


In [9]:
print(np.kron(b, a))   # 计算 b a 的张量积

[[11 11 12 12]
 [11 11 12 12]
 [21 21 22 22]
 [21 21 22 22]]


In [1]:
from mindquantum import Simulator, Circuit, X, Y
import numpy as np
s0 = np.array([0.1, 0.4])   # 任意态
sim = Simulator('projectq', 1)   # 声明一个 1 比特的模拟器
sim.set_qs(s0)   # 设置量子态
print(sim.get_qs())   # 查看量子态

[0.24253563+0.j 0.9701425 +0.j]


In [2]:
sim.apply_gate(X.on(0))   # 作用一个 X 门到 0 号比特上
print(sim.get_qs())    # 查看量子态
#  其应由 [a, b] 变换至 [b, a]


[0.9701425 +0.j 0.24253563+0.j]


In [3]:
sim.apply_gate(Y.on(0))   # 再作用一个 Y 门到 0 号比特上
print(sim.get_qs())    # 查看量子态
#  其应由 [a, b] 变换至 [-b · i, a · i]

[0.-0.24253563j 0.+0.9701425j ]
