In [4]:
from mindquantum import*

In [5]:
H

H

In [6]:
H(0,1)

H(0 <-: 1)

In [7]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [8]:
import numpy as np

In [9]:
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [10]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [11]:
circuit = Circuit([H.on(0),X.on(1,0)])

In [12]:
circuit

q0: ──H────●──
           │
q1: ───────X──

In [13]:
circuit += qft(**range**(2))

TypeError: unsupported operand type(s) for ** or pow(): 'type' and 'int'

In [ ]:
circuit

In [15]:
**print**(circuit.get_qs(ket = True))

SyntaxError: invalid syntax (1385248697.py, line 1)

In [16]:
sim = Simulator('projectq',3)

In [17]:
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [18]:
sim.apply_circuit(qft(**range**(3)))

TypeError: unsupported operand type(s) for ** or pow(): 'type' and 'int'

In [19]:
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [20]:
sim.reset()

In [21]:
circuit = Circuit([H.on(0), H.on(1), H.on(2)]) + qft(**range**(3))

TypeError: unsupported operand type(s) for ** or pow(): 'type' and 'int'

In [22]:
sim.apply_circuit(circuit)

In [23]:
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/2¦000⟩
√2/2¦011⟩

In [24]:
circuit

q0: ──H────●──
           │
q1: ───────X──