In [4]:
from mindquantum import *

In [5]:
H(0, 1)

H(0 <-: 1)

In [6]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [7]:
import numpy as np

In [8]:
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [9]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [10]:
circuit = Circuit([H.on(0), X.on(1,0)])
circuit

q0: ──H────●──
           │
q1: ───────X──

In [11]:
circuit += qft(range(2))
circuit

q0: ──H────●────H────PS(π/2)─────────@──
           │            │            │
q1: ───────X────────────●───────H────@──

In [12]:
print(circuit.get_qs(ket=True))

√2/2¦00⟩
(√2/4-√2/4j)¦10⟩
(√2/4+√2/4j)¦11⟩


In [17]:
sim = Simulator('projectq', 3)
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [28]:
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [29]:
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [30]:

sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [22]:
sim.reset()
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [32]:
sim.reset()
sim.apply_gate(X.on(1))
print(sim)
sim.apply_circuit(qft(range(3)))
print(sim)
sim.apply_circuit(qft(range(3)).hermitian())
print(sim) 

projectq simulator with 3 qubits.
Current quantum state:
1¦010⟩
projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
-√2/4¦010⟩
-√2/4¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
-√2/4j¦110⟩
-√2/4j¦111⟩
projectq simulator with 3 qubits.
Current quantum state:
1¦010⟩


In [33]:
sim.reset()

circuit = Circuit([H.on(0), H.on(1), H.on(2)]) + qft(range(3))
sim.apply_circuit(circuit)
sim 

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [34]:
circuit

q0: ──H────H────PS(π/2)────PS(π/4)─────────────────────────@──
                   │          │                            │
q1: ──H────────────●──────────┼───────H────PS(π/2)─────────┼──
                              │               │            │
q2: ──H───────────────────────●───────────────●───────H────@──

In [ ]:
import networkx as nx
