In [1]:
from mindquantum import *

In [2]:
H

H

In [3]:
H(0)

H(0)

In [4]:
H(0, 1)

H(0 <-: 1)

In [5]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [7]:
import numpy as np
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [8]:
RX('theta')

RX(theta)

In [10]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [12]:
Circuit()

In [13]:
Circuit([H.on(0)])

q0: ──H──

In [15]:
Circuit([H.on(0), X.on(1, 0)])

q0: ──H────●──
           │
q1: ───────X──

In [16]:
circuit = Circuit([H.on(0), X.on(1, 0)])
circuit

q0: ──H────●──
           │
q1: ───────X──

In [19]:
circuit += qft((range(2)))
circuit

q0: ──H────●────H────PS(π/2)─────────@────H────PS(π/2)─────────@────H────PS(π/2)─────────@──
           │            │            │            │            │            │            │
q1: ───────X────────────●───────H────@────────────●───────H────@────────────●───────H────@──

In [20]:
circuit.get_qs()

array([0.70710678+0.j        , 0.        +0.j        ,
       0.35355339+0.35355339j, 0.35355339-0.35355339j])

In [22]:
print(circuit.get_qs(ket=True))

√2/2¦00⟩
(√2/4+√2/4j)¦10⟩
(√2/4-√2/4j)¦11⟩


In [23]:
sim = Simulator('projectq', 3)
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [26]:
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [28]:
sim.reset()
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [33]:
sim.set_qs(Circuit([H.on(0), H.on(1), H.on(2)]).get_qs()*1j)

In [34]:
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4j¦000⟩
√2/4j¦001⟩
√2/4j¦010⟩
√2/4j¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
√2/4j¦110⟩
√2/4j¦111⟩