In [2]:
from mindquantum import *

In [2]:
H

H

In [3]:
H(0,1)

H(0 <-: 1)

In [5]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [3]:
import numpy as np
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [12]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [4]:
circuit = Circuit([H.on(0), X.on(1,0)])
circuit 

q0: ──H────●──
           │
q1: ───────X──

In [5]:
circuit += qft(range(2))
circuit

q0: ──H────●────H────PS(π/2)─────────@──
           │            │            │
q1: ───────X────────────●───────H────@──

In [6]:
print(circuit.get_qs(ket=True))#get quantum state,ket 是矢量表达

√2/2¦00⟩
(√2/4-√2/4j)¦10⟩
(√2/4+√2/4j)¦11⟩


In [8]:
sim = Simulator('projectq',3)
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [9]:
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [10]:
sim.reset()

In [25]:
#qft作用在均匀叠加态上会产生什么结果
#制备均匀叠加态(H门作用到所有量子态上就产生均匀叠加态)
sim = Simulator('projectq',3)
# sim.apply_circuit(qft(range(3)))
sim.apply_circuit(Circuit().un(H, 3))
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [30]:
sim.set_qs(Circuit([H.on(0),H.on(1),H.on(2)]).get_qs())
sim
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [32]:
#标准答案
sim.reset()

circuit = Circuit([H.on(0),H.on(1),H.on(2)])
sim.apply_circuit(circuit)
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩