In [1]:
from mindquantum import *

In [2]:
H

H

In [3]:
H(0,1)

H(0 <-: 1)

In [4]:
H.matrix

<bound method NoneParameterGate.matrix of H>

In [5]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [8]:
import numpy as np
RX(np.pi).matrix()


array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [10]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [27]:
circuit = Circuit([H.on(0),X.on(1.0)])
circuit

TypeError: Excepted int, list or tuple for                 obj_qubits, but get <class 'float'>

In [31]:
circuit += qft(range(2))
circuit

NameError: name 'circuit' is not defined

In [23]:
print(circuit.get_qs(ket=True))

NameError: name 'circuit' is not defined

In [25]:
sim = Simulator('projectq',3)
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [29]:
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [30]:
sim.reset()

In [32]:
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [34]:
sim.set_qs(Circuit([H.on(0),H.on(1),H.on(2)]).get_qs())
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4j¦000⟩
√2/4j¦001⟩
√2/4j¦010⟩
√2/4j¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
√2/4j¦110⟩
√2/4j¦111⟩

In [35]:
sim.apply_circuit(qft(range(3)))

In [36]:
sim

projectq simulator with 3 qubits.
Current quantum state:
1j¦000⟩

In [37]:
circuit

NameError: name 'circuit' is not defined

In [38]:
sim.reset()

circuit = Circuit([H.on(0), H.on(1), H.on(2)]) + qft(range(3))
sim.apply_circuit(circuit)
sim 


projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [39]:
circuit

q0: ──H────H────PS(π/2)────PS(π/4)─────────────────────────@──
                   │          │                            │
q1: ──H────────────●──────────┼───────H────PS(π/2)─────────┼──
                              │               │            │
q2: ──H───────────────────────●───────────────●───────H────@──