In [2]:
from mindquantum import *

In [3]:
H

H

In [4]:
H(0, 1) # 受控h门

H(0 <-: 1)

In [5]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
import numpy as np
RX(np.pi).matrix() # 绕x旋转pi


array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [7]:
RX('theta').matrix({'theta': np.pi}) # 参数化

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [8]:
Circuit([H.on(0), X.on(1,ctrl_qubits=0)])

q0: ──H────●──
           │
q1: ───────X──

In [9]:
circuit = Circuit([H.on(0), X.on(1,ctrl_qubits=0)])
circuit

q0: ──H────●──
           │
q1: ───────X──

In [10]:
circuit += qft(range(2)) # 量子傅里叶

In [11]:
circuit

q0: ──H────●────H────PS(π/2)─────────@──
           │            │            │
q1: ───────X────────────●───────H────@──

In [12]:
circuit.get_qs()  # 获取量子态

array([0.70710678+0.j        , 0.        +0.j        ,
       0.35355339-0.35355339j, 0.35355339+0.35355339j])

In [13]:
print(circuit.get_qs(ket=True)) #识别无理数表示

√2/2¦00⟩
(√2/4-√2/4j)¦10⟩
(√2/4+√2/4j)¦11⟩


In [14]:
sim = Simulator(backend='projectq', n_qubits=3) # 支持不同模拟器
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [15]:
sim.apply_circuit(qft(range(3))) # 0态作用量子傅里叶变换  点 --》 线
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
√2/4¦010⟩
√2/4¦011⟩
√2/4¦100⟩
√2/4¦101⟩
√2/4¦110⟩
√2/4¦111⟩

In [16]:
# API 文档：
# https://gitee.com/mindspore/mindquantum/blob/master/README_CN.md#api
# https://www.mindspore.cn/mindquantum/api/zh-CN/master/index.html

In [17]:
sim.reset() # 重置模拟器
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [18]:
# task 1  量子傅里叶变换作用在均匀叠加态上 产生的量子态：
# sim.apply_circuit(qft(range(3))).apply_circuit(qft(range(3)))
sim.reset()
sim.set_qs(Circuit([H.on(0), H.on(1), H.on(2)]).get_qs()*1j)
sim

projectq simulator with 3 qubits.
Current quantum state:
√2/4j¦000⟩
√2/4j¦001⟩
√2/4j¦010⟩
√2/4j¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
√2/4j¦110⟩
√2/4j¦111⟩

In [19]:
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1j¦000⟩

In [20]:
sim.reset()
sim.apply_gate(X.on(1))
print(sim)
sim.apply_circuit(qft(range(3)))
print(sim)
sim.apply_circuit(qft(range(3))) # 厄密共轭抵消
print(sim)

projectq simulator with 3 qubits.
Current quantum state:
1¦010⟩
projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
-√2/4¦010⟩
-√2/4¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
-√2/4j¦110⟩
-√2/4j¦111⟩
projectq simulator with 3 qubits.
Current quantum state:
1¦011⟩


In [40]:
sim.reset()
sim.apply_gate(X.on(1))
print(sim)
sim.apply_circuit(qft(range(3)))
print(sim)
sim.apply_circuit(qft(range(3)).hermitian) # 厄密共轭抵消
print(sim)

projectq simulator with 3 qubits.
Current quantum state:
1¦010⟩
projectq simulator with 3 qubits.
Current quantum state:
√2/4¦000⟩
√2/4¦001⟩
-√2/4¦010⟩
-√2/4¦011⟩
√2/4j¦100⟩
√2/4j¦101⟩
-√2/4j¦110⟩
-√2/4j¦111⟩
projectq simulator with 3 qubits.
Current quantum state:
1¦011⟩


In [42]:
sim.reset()
sim.apply_circuit(qft(range(3)))
sim.apply_circuit(qft(range(3)))
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩

In [21]:
sim.reset()
c = Circuit([H.on(0), H.on(1),H.on(2)]) + qft(range(3))
c
# sim.apply_circuit()

q0: ──H────H────PS(π/2)────PS(π/4)─────────────────────────@──
                   │          │                            │
q1: ──H────────────●──────────┼───────H────PS(π/2)─────────┼──
                              │               │            │
q2: ──H───────────────────────●───────────────●───────H────@──

In [23]:
sim.apply_circuit(c)
sim

projectq simulator with 3 qubits.
Current quantum state:
1¦000⟩