# 2小时MindQuantum从入门到精通

In [1]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

/home/xuxs/gitee/mindquantum/mindquantum/__init__.py:49: UserWarning: [NOTE] Current simulator thread is 16. If your simulation is slow, set OMP_NUM_THREADS to a appropriate number according to your model.
  warnings.warn(


## 初识量子门

In [2]:
print(H)
print(H.matrix())
print(H.on(0))

H
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
H(0)


In [3]:
print(X.matrix())
print(X.on(1, 0))

[[0 1]
 [1 0]]
X(1 <-: 0)


In [4]:
print(RX(np.pi))
print(RX(np.pi).matrix())
print(RX('a'))
print(RX({'a':1.5, 'b':2}))
print(RX({'a':1.5, 'b':2}).matrix({'a':0, 'b':np.pi/2}))

RX(π)
[[6.123234e-17+0.j 0.000000e+00-1.j]
 [0.000000e+00-1.j 6.123234e-17+0.j]]
RX(a)
RX(1.5*a + 2*b)
[[6.123234e-17+0.j 0.000000e+00-1.j]
 [0.000000e+00-1.j 6.123234e-17+0.j]]


## 初识量子线路

In [5]:
circuit = Circuit()

In [6]:
circuit = Circuit([H.on(0), X.on(1, 0)])
circuit

q0: ──H────●──
           │  
q1: ───────X──

In [7]:
circuit += RX('a').on(1)
circuit

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──

In [8]:
qft(range(4))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────

## 初识模拟器

In [9]:
sim = Simulator('projectq', 4)
sim.get_qs()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [10]:
sim.apply_circuit(qft(range(4)))

In [11]:
sim.get_qs()

array([0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
       0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
       0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j])

In [12]:
sim = Simulator('projectq', 4)
sim.apply_gate(X.on(2))
sim.flush()
sim.get_qs()

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [13]:
bin(4)[2:].zfill(4)

'0100'

In [14]:
sim.apply_circuit(qft(range(4)))
sim.get_qs()

array([ 2.50000000e-01+0.j       ,  2.50000000e-01+0.j       ,
       -2.50000000e-01+0.j       , -2.50000000e-01+0.j       ,
        1.53080850e-17+0.25j     ,  1.53080850e-17+0.25j     ,
       -1.53080850e-17-0.25j     , -1.53080850e-17-0.25j     ,
        1.76776695e-01+0.1767767j,  1.76776695e-01+0.1767767j,
       -1.76776695e-01-0.1767767j, -1.76776695e-01-0.1767767j,
       -1.76776695e-01+0.1767767j, -1.76776695e-01+0.1767767j,
        1.76776695e-01-0.1767767j,  1.76776695e-01-0.1767767j])

In [15]:
np.abs(sim.get_qs())

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
       0.25, 0.25, 0.25, 0.25, 0.25])

In [16]:
circuit

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──

In [17]:
sim = Simulator('projectq', 2)
sim.apply_circuit(circuit, {'a':0})
sim.get_qs()

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

## 相位估计

In [18]:
n = 10
c = Circuit()
c += UN(H, n)
for i in range(n):
    c += RZ({'Θ': 2**i}).on(n, n-i-1)
c

q0:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────●──────
                                                                                                                        │      
q1:  ──H───────────────────────────────────────────────────────────────────────────────────────────────────●────────────┼──────
                                                                                                           │            │      
q2:  ──H──────────────────────────────────────────────────────────────────────────────────────●────────────┼────────────┼──────
                                                                                              │            │            │      
q3:  ──H─────────────────────────────────────────────────────────────────────────●────────────┼────────────┼────────────┼──────
                                                                                 │            │            │            │      
q4:  ──H─────────────────────────────────────────────────────────────●───────────┼────────────┼────────────┼────────────┼──────
                                                                     │           │            │            │            │      
q5:  ──H─────────────────────────────────────────────────●───────────┼───────────┼────────────┼────────────┼────────────┼──────
                                                         │           │           │            │            │            │      
q6:  ──H──────────────────────────────────────●──────────┼───────────┼───────────┼────────────┼────────────┼────────────┼──────
                                              │          │           │           │            │            │            │      
q7:  ──H───────────────────────────●──────────┼──────────┼───────────┼───────────┼────────────┼────────────┼────────────┼──────
                                   │          │          │           │           │            │            │            │      
q8:  ──H────────────────●──────────┼──────────┼──────────┼───────────┼───────────┼────────────┼────────────┼────────────┼──────
                        │          │          │          │           │           │            │            │            │      
q9:  ──H──────●─────────┼──────────┼──────────┼──────────┼───────────┼───────────┼────────────┼────────────┼────────────┼──────
              │         │          │          │          │           │           │            │            │            │      
q10: ───────RZ(Θ)────RZ(2*Θ)────RZ(4*Θ)────RZ(8*Θ)────RZ(16*Θ)────RZ(32*Θ)────RZ(64*Θ)────RZ(128*Θ)────RZ(256*Θ)────RZ(512*Θ)──

In [19]:
c += BARRIER
c += qft(range(n)).hermitian
c

q0:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────●──────‖──────────────────────✖───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/512)────PS(-π/256)────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H──
                                                                                                                        │      ‖                      │                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       │             │             │             │            │            │           │           │           │           
q1:  ──H───────────────────────────────────────────────────────────────────────────────────────────────────●────────────┼──────‖─────────────────✖────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/256)────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H────────┼─────────────┼─────────────┼─────────────┼────────────┼────────────┼───────────┼───────────┼───────────●───────────
                                                                                                           │            │      ‖                 │    │                                                                                                                                                                                                                                                                                                                                                                                                           │             │             │            │            │           │           │           │                 │             │             │             │            │            │           │           │                       
q2:  ──H──────────────────────────────────────────────────────────────────────────────────────●────────────┼────────────┼──────‖────────────✖────┼────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H────────┼─────────────┼─────────────┼────────────┼────────────┼───────────┼───────────┼───────────●─────────────────┼─────────────┼─────────────┼─────────────┼────────────┼────────────┼───────────┼───────────●───────────────────────
                                                                                              │            │            │      ‖            │    

In [20]:
sim = Simulator('projectq', c.n_qubits)
sim.apply_circuit(c,{'Θ': -4*np.pi*0.154897863})

In [21]:
qs = sim.get_qs()
qs

array([0.00024158+0.00193748j, 0.00102505-0.00012781j,
       0.00190521-0.00244801j, ..., 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ])

In [22]:
index = np.argmax(np.abs(qs))
print(index)
bit_string = bin(index)[2:].zfill(c.n_qubits)[1:]
print(bit_string)

996
1111100100


In [23]:
theta_exp = int(bit_string[::-1], 2) / 2**n
theta_exp

0.1552734375