In [15]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

In [16]:

H.matrix()


array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [17]:
H.on(0)

H(0)

In [18]:
X.on(1,0)

X(1 <-: 0)

In [19]:
RX(np,pi).matrix()

NameError: name 'pi' is not defined

## 

In [20]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [21]:
RX({'a':2,'b':1})

RX(2*a + b)

# Do it yourself
验证均匀叠加态经过傅里叶变换后的量子态为零态

In [22]:
circuit=Circuit()
print(circuit)

In [23]:
circuit = Circuit([H.on(0),X.on(1,0)])
print(circuit)

q0: ──H────●──
           │  
q1: ───────X──


In [24]:
circuit+=RX('a').on(1)

In [25]:
print(circuit)

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──


In [26]:
print(qft(range(4)))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [27]:
sim=Simulator('projectq',10)

In [28]:
sim.apply_circuit(qft(range(10)))
print(sim.get_qs())

[0.03125+0.j 0.03125+0.j 0.03125+0.j ... 0.03125+0.j 0.03125+0.j
 0.03125+0.j]


In [29]:
sim =Simulator('projectq',4)
sim.apply_circuit(Circuit([H.on(1),H.on(2),H.on(3)]))
sim.apply_circuit(qft(range(4)))
print(sim.get_qs())

[ 7.07106781e-01+0.j         -2.77555756e-17+0.j
  0.00000000e+00+0.j          0.00000000e+00+0.j
  0.00000000e+00+0.j          0.00000000e+00+0.j
  0.00000000e+00+0.j          0.00000000e+00+0.j
  8.83883476e-02+0.44435823j  8.83883476e-02-0.01758154j
  8.83883476e-02+0.05905921j  8.83883476e-02-0.13228251j
  8.83883476e-02+0.13228251j  8.83883476e-02-0.05905921j
  8.83883476e-02+0.01758154j  8.83883476e-02-0.44435823j]


In [30]:
n = 10
c = Circuit()
c += UN(H, n)
for i in range(n):
    c += RZ({'theta': 2**i}).on(n, n-i-1)
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────
                                                                                                                                                              │        
q1:  ──H─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────
                                                                                                                                             │                │        
q2:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────────────┼────────
                                                                                                                            │                │                │ 

In [31]:
c += qft(range(n)).hermitian
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●──────────────────────────────✖───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/512)────PS(-π/256)────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H──
                                                                                                                                                              │                              │

In [32]:
sim = Simulator('projectq', c.n_qubits)

In [33]:
sim.apply_circuit(c, {'theta': -4*np.pi*0.1234})
qs=sim.get_qs()
qs

array([ 1.71694568e-03+0.00159414j,  6.50947904e-04-0.00070109j,
       -8.47511981e-05-0.00228515j, ...,  0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        ,  0.00000000e+00+0.j        ])

In [34]:
index = np.argmax(np.abs(qs))
print(index)
bit_string = bin(index)[2:].zfill(c.n_qubits)[1:]
print(bit_string)

504
0111111000


In [35]:
theta_exp = int(bit_string[::-1], 2) / 2**n
theta_exp

0.123046875

In [36]:
c += qft(range(n)).hermitian
print(c)

                                                           │                │                │                │               │    │    │    │                                                                                                                                                                                                                             │            │            │           │           │           │                 │             │            │            │           │           │                             │             │             │            │            │           │                                         │             │             │             │            │            │                       │           │        │    │                                                                                                                                                                                                                             │            │ 

In [37]:
index = np.argmax(np.abs(qs))
print(index)
bit_string = bin(index)[2:].zfill(c.n_qubits)[1:]
print(bit_string)

504
0111111000


In [38]:
theta_exp = int(bit_string[::-1], 2) / 2**n
theta_exp

0.123046875

In [39]:
theta_exp = int(bit_string[::-1], 2) / 2**n
theta_exp

0.123046875