In [1]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

## 

In [2]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [3]:
H.on(0)

H(0)

In [4]:
X.on(1, 0)

X(1 <-: 0)

In [5]:
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [6]:
RX("theta").matrix({"theta":np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [7]:
RX({'a':2, 'b':1})

RX(2*a + b)

In [8]:
circult = Circuit()
print(circult)

In [9]:
circult = Circuit([H.on(0), X.on(1, 0)])
print(circult)

q0: ──H────●──
           │  
q1: ───────X──


In [10]:
circult += RX('a').on(1)
print(circult)

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──


In [11]:
print(qft(range(4)))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [12]:
sim = Simulator("projectq", 4)

In [13]:
sim.apply_circuit(qft(range(4)))
print(sim.get_qs())

[0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j
 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j]


In [14]:
sim = Simulator('projectq', 4)
sim.apply_circuit(Circuit([H.on(0), H.on(1), H.on(2), H.on(3)]))
sim.apply_circuit(qft(range(4)))
print(sim.get_qs())

[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [15]:
n = 10
c = Circuit()
c += UN(H, n)
for i in range(n):
    c += RZ({"theta": 2**i}).on(n, n-i-1)
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────
                                                                                                                                                              │        
q1:  ──H─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────
                                                                                                                                             │                │        
q2:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────────────┼────────
                                                                                                                            │                │                │ 

In [18]:
c += qft(range(n)).hermitian
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●──────────────────────────────✖───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/512)────PS(-π/256)────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H──
                                                                                                                                                              │                              │