In [1]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

## 

In [3]:
H.on(0).matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [4]:
X.on(1,0)

X(1 <-: 0)

In [7]:
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [9]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [10]:
RX({'a':1,'b':2})

RX(a + 2*b)

In [ ]:
circuit = Circuit()

In [12]:
circuit=Circuit([H.on(0),X.on(1,0)])
print(circuit)

q0: ──H────●──
           │  
q1: ───────X──


In [13]:
circuit+=RX('a').on(1)
print(circuit)

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──


In [15]:
print(qft(range(4)))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [17]:
sim = Simulator('projectq',4)
sim.get_qs()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [18]:
sim.apply_circuit(qft(range(4)))
sim.get_qs()

array([0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
       0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j,
       0.25+0.j, 0.25+0.j, 0.25+0.j, 0.25+0.j])

# Do it yourself
验证均匀叠加态经过傅里叶变换后的量子态为零态

In [22]:
circuit1=Circuit([H.on(0),H.on(1),H.on(2)])
print(circuit1)


q0: ──H──
         
q1: ──H──
         
q2: ──H──


In [24]:
sim = Simulator('projectq',3)
sim.apply_circuit(circuit1)
sim.apply_circuit(qft(range(3)))
sim.get_qs()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])