In [63]:
import os

os.environ['OMP_NUM_THREADS'] = '2'
from sklearn import datasets
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np

np.random.seed(42)


def generate_train_and_test(split=0.8, shuffle=True):
    iris = datasets.load_iris()
    data = iris.data[:100, :].astype(np.float32)
    data = preprocessing.minmax_scale(data) * 2 - 1
    label = np.zeros(100).astype(int)
    label[50:] = 1
    return train_test_split(data, label, train_size=split, shuffle=shuffle)


train_x, test_x, train_y, test_y = generate_train_and_test(split=0.2)
print('train sample and feature shape: ', train_x.shape)
print('first train sample: ', train_x[0, :], ' with label: ', train_y[0])

train sample and feature shape:  (20, 4)
first train sample:  [ 0.33333302 -0.24999988  0.804878    0.5294118 ]  with label:  1


In [64]:
from mindquantum import H, RZ, RX, X, Circuit, RY, UN


def encoder(n):
    c = Circuit()
    #create your new encoder here
    for i in range(n):
        c += RX(f'x{i}').on(i)
    return c


enc = encoder(4).no_grad()
print("encoder circuit:")
print(enc)
print("\n")

def ansatz(n_qubits):
    c = Circuit()
    # create your new ansatz here:
    for i in range(n_qubits):
        c += RX(f"gamma{i}").on(i)
    return c


ans = ansatz(4)
print("ansatz circuit:")
print(ans)
if len(ans) > 15:
    raise ValueError(
        "Too many gates in the ansatz circuit, we limited it to 15 gate.")
tot = enc + ans
print("\ntotal circuit:")
print(tot)

encoder circuit:
q0: ──RX(x0)──
              
q1: ──RX(x1)──
              
q2: ──RX(x2)──
              
q3: ──RX(x3)──


ansatz circuit:
q0: ──RX(gamma0)──
                  
q1: ──RX(gamma1)──
                  
q2: ──RX(gamma2)──
                  
q3: ──RX(gamma3)──

total circuit:
q0: ──RX(x0)────RX(gamma0)──
                            
q1: ──RX(x1)────RX(gamma1)──
                            
q2: ──RX(x2)────RX(gamma2)──
                            
q3: ──RX(x3)────RX(gamma3)──


In [65]:
from mindquantum.ops import QubitOperator
from mindquantum import Hamiltonian

hams = [Hamiltonian(QubitOperator(f'Z{i}')) for i in [2, 3]]
print(hams)

[1.0 [Z2] , 1.0 [Z3] ]


In [66]:
from mindquantum import Simulator
sim = Simulator('projectq', tot.n_qubits)
f_g_ops = sim.get_expectation_with_grad(hams, tot,encoder_params_name=enc.params_name,ansatz_params_name=ans.params_name, parallel_worker=4)

In [67]:
p0 = np.random.uniform(size=len(ans.params_name))
f_g_ops(train_x[:1], p0)

(array([[-0.02425483+0.j,  0.42179538+0.j]]),
 array([[[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]]),
 array([[[ 1.54498810e-17+0.j, -1.30104261e-17+0.j, -9.99705808e-01+0.j,
           0.00000000e+00+0.j],
         [-9.44611143e-18+0.j, -3.67002435e-17+0.j,  6.74915852e-17+0.j,
          -9.06691047e-01+0.j]]]))

In [68]:
import mindspore as ms
from mindquantum.nn import MQLayer
ms.context.set_context(mode=ms.context.PYNATIVE_MODE, device_target="CPU")
ms.set_seed(42)
net = MQLayer(f_g_ops)

In [69]:
from mindspore import Tensor
print('QNN output: \n', net(Tensor(train_x[:4])))
print('\nweight: \n', net.weight.asnumpy())

QNN output: 
 [[0.68977344 0.87000996]
 [0.7570179  0.80612576]
 [0.69660926 0.5286067 ]
 [0.7631809  0.6245892 ]]

weight: 
 [ 0.00495268 -0.00754737  0.00474223 -0.01383794]


In [70]:
import mindspore.dataset as ds
ms.set_seed(42)

batch = 5
train_loader = ds.NumpySlicesDataset({
    'feats': train_x,
    'labs': train_y
},
                                     shuffle=False).batch(batch)
test_loader = ds.NumpySlicesDataset({
    'feats': test_x,
    'labs': test_y
}).batch(batch)

In [71]:
loss = ms.nn.SoftmaxCrossEntropyWithLogits(sparse=True, reduction='mean')
opti = ms.nn.Adam(net.trainable_params(), learning_rate=1e-1)
monitor = ms.train.callback.LossMonitor(16)

In [72]:
model = ms.Model(net, loss, opti, metrics={'Acc': ms.nn.Accuracy()})
model.train(50, train_loader, callbacks=[monitor], dataset_sink_mode=False)

epoch: 4 step: 4, loss is 0.31389818
epoch: 8 step: 4, loss is 0.26366514
epoch: 12 step: 4, loss is 0.2762904
epoch: 16 step: 4, loss is 0.27422777
epoch: 20 step: 4, loss is 0.27375117
epoch: 24 step: 4, loss is 0.27409387
epoch: 28 step: 4, loss is 0.2736756
epoch: 32 step: 4, loss is 0.2739952
epoch: 36 step: 4, loss is 0.27390555
epoch: 40 step: 4, loss is 0.27395308
epoch: 44 step: 4, loss is 0.273955
epoch: 48 step: 4, loss is 0.2739719


In [73]:
predict = np.argmax(ms.ops.Softmax()(model.predict(ms.Tensor(test_x))), axis=1)
corr = model.eval(test_loader, dataset_sink_mode=False)
print(corr)

{'Acc': 1.0}
