In [2]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

## 

In [5]:
H.matrix()



array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
H.on(0)

H(0)

In [7]:
X.on(1,0)

X(1 <-: 0)

In [8]:
RX(np.pi).matrix()

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [9]:
RX('theta').matrix({'theta':np.pi})


array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [10]:
RX({'a':2,'b':1})

RX(2*a + b)

In [13]:
circuit = Circuit()
print(circuit)

In [14]:
circuit=Circuit([H.on(0),X.on(1,0)])
print(circuit)

q0: ──H────●──
           │  
q1: ───────X──


In [16]:
circuit+=RX('a').on(1)

In [17]:
print(circuit)

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──


In [23]:
print(qft(range(4)))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [19]:
sim=Simulator('projectq',4)

In [20]:
sim.apply_circuit(qft(range(4)))
print(sim.get_qs())


[0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j
 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j]


# Do it yourself
验证均匀叠加态经过傅里叶变换后的量子态为零态

In [25]:
sim=Simulator('projectq',4)
sim.apply_circuit(Circuit([H.on(0),H.on(1),H.on(2),H.on(3)]))
sim.apply_circuit(qft(range(4)))
print(sim.get_qs())

[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [26]:
n=10
c=Circuit()
c+=UN(H,n)
for i in range(n):
    c+=RZ({'theta':2**i}).on(n,n-i-1)
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────
                                                                                                                                                              │        
q1:  ──H─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────
                                                                                                                                             │                │        
q2:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────────────┼────────
                                                                                                                            │                │                │ 

In [27]:
c+=qft(range(n)).hermitian
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●──────────────────────────────✖───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────PS(-π/512)────PS(-π/256)────PS(-π/128)────PS(-π/64)────PS(-π/32)────PS(-π/16)────PS(-π/8)────PS(-π/4)────PS(-π/2)────H──
                                                                                                                                                              │                              │

In [30]:
sim=Simulator('projectq',c.n_qubits)

In [31]:
sim.apply_circuit(c,{'theta':-4*np.pi*0.1234})

In [32]:
qs=sim.get_qs()


In [33]:
qs

array([ 1.71694568e-03+0.00159414j,  6.50947904e-04-0.00070109j,
       -8.47511981e-05-0.00228515j, ...,  0.00000000e+00+0.j        ,
        0.00000000e+00+0.j        ,  0.00000000e+00+0.j        ])