In [1]:
from mindquantum import Circuit, Simulator
from mindquantum import RZ, UN, H, X, Y, Z, RX, RY, RZ, BARRIER, qft
import numpy as np

## 

In [4]:
H.matrix()

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [5]:
H.on(0)

H(0)

In [7]:
X.on(1, 0)

X(1 <-: 0)

In [9]:
RX(np.pi).matrix()


array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [12]:
RX('theta').matrix({'theta':np.pi})

array([[6.123234e-17+0.j, 0.000000e+00-1.j],
       [0.000000e+00-1.j, 6.123234e-17+0.j]])

In [13]:
RX({'a':2, 'b':1})

RX(2*a + b)

In [14]:
circuit = Circuit()
print(circuit)

In [17]:
circuit = Circuit([H.on(0), X.on(1, 0)])
print(circuit)

q0: ──H────●──
           │  
q1: ───────X──


In [18]:
circuit += RX('a').on(1)

In [19]:
print(circuit)

q0: ──H────●───────────
           │           
q1: ───────X────RX(a)──


In [22]:
print(qft(range(4)))

q0: ──H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
              │          │          │                                                       │       
q1: ──────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                         │          │               │          │                            │    │  
q2: ─────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                    │                          │               │            │       
q3: ────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [23]:
sim  = Simulator('projectq', 4)

In [25]:
sim.apply_circuit(qft(range(4)))
sim.get_qs()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

# Do it yourself
验证均匀叠加态经过傅里叶变换后的量子态为零态

In [31]:
my_circuit = Circuit([H.on(0), H.on(1), H.on(2), H.on(3)])
my_circuit += qft(range(4))
print(my_circuit)

q0: ──H────H────PS(π/2)────PS(π/4)────PS(π/8)────────────────────────────────────────────────────✖───────
                   │          │          │                                                       │       
q1: ──H────────────●──────────┼──────────┼───────H────PS(π/2)────PS(π/4)─────────────────────────┼────✖──
                              │          │               │          │                            │    │  
q2: ──H───────────────────────●──────────┼───────────────●──────────┼───────H────PS(π/2)─────────┼────✖──
                                         │                          │               │            │       
q3: ──H──────────────────────────────────●──────────────────────────●───────────────●───────H────✖───────


In [32]:
my_sim  = Simulator('projectq', 4)
my_sim.apply_circuit(my_circuit)
my_sim.get_qs()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [38]:
n = 10
c = Circuit()
c += UN(H, n)
for i in range (n):
    c += RZ({'theta': 2**i}).on(n, n-i-1)
print(c)

q0:  ──H──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────
                                                                                                                                                              │        
q1:  ──H─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────
                                                                                                                                             │                │        
q2:  ──H────────────────────────────────────────────────────────────────────────────────────────────────────────────────────●────────────────┼────────────────┼────────
                                                                                                                            │                │                │ 

In [40]:
c += qft(range(n)).hermitian
print(c)

                                                           │                │                │                │               │    │    │    │                                                                                                                                                                                                                             │            │            │           │           │           │                 │             │            │            │           │           │                             │             │             │            │            │           │                                         │             │             │             │            │            │                       │           │        │    │                                                                                                                                                                                                                             │            │ 

In [42]:
sim = Simulator('projectq', c.n_qubits)

In [ ]:
sim.apply_circuit(c, {'theta': -4*np.pi*0.1234})
